site_name: MyGPT
site_url: https://mygpt.stjude.org
theme:
  palette:
    primary: cyan
nav:
  - Home: index.md
  - Installation: installation/README.md
  - Developer's Guide: development.md
  - FAQs: FAQs.md
  - Contact: contact.md