site_name: MyGPT
site_url: https://mygpt.stjude.org
theme:
  name: material
  palette:
    primary: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
  plugins:
    - search
nav:
  - Home: index.md
  - Installation: installation/README.md
  - Developer's Guide: development.md
  - FAQs: FAQs.md
  - Contact: contact.md